env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins: []
rules: 
  "require-jsdoc" : 0
  "camelcase" : 0
